version: "3.9"

services:
  app:
    image: python-instascrapper:local-dev
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    stdin_open: true
    tty: true
    command: python3 ./instaScrapper.py
    volumes:
      - .:/app:delegated
    networks:
      - default
